### ISSUE TITLE
Bump palette-derive version

### ISSUE THREAD

**Issue by ishitatsuyuki** [Ogeon/palette#145]
It seems it has been a year since `syn` was upgraded to `0.15` (#122) but a version bump hasn't happened yet.

**Comment by Ogeon** [comment]
You are right, it has been quite some time since the previous release, for various reasons. I'm currently waiting for num_traits to get improved no_std support (see https://github.com/rust-num/num-traits/pull/99). But it should be pretty much good to go after that! 🙂

I do also do it a bit differently from what is probably common, when it comes to changing the version number. I change the version just before releasing. So it will happen when the time is right.

I hope there isn't any problem with the currently released version...

**Comment by malobre** [comment]
https://github.com/rust-num/num-traits/pull/99 was merged.
Related: https://github.com/rust-num/num-traits/issues/75#issuecomment-544223735
I hope they will publish to crates.io soon so we can finally get that shiny new palette version :)

**Comment by malobre** [comment]
https://github.com/rust-num/num-traits/issues/75 has been closed and num-traits 0.2.9 has been published on crates.io

**Comment by Ogeon** [comment]
Excellent! I will try to get a release out soon, but I don't think I will have the time at least before the weekend. Hopefully there's nothing else in the way...

**Comment by Ogeon** [comment]
Done!
