### ISSUE TITLE
Problems with examples

### ISSUE THREAD

**Issue by darakshan** [Ogeon/palette#185]
Running most or all of the examples from a clean pull fail for two reasons.  For example, try 
`cargo run --example hue`

> thread 'main' panicked at 'could not open 'res/fruits.png': UnsupportedError("A decoder for PNG is not available.")', palette/examples/hue.rs:4:21

I corrected this by setting `default-features = true` in `[dev-dependencies.image]`

Example hue then fails with:
> failed to write 'examples/hue.png': No such file or directory (os error 2)

This was confusing because I can run cargo from `palette` or `palette/palette`, and could find no instructions about which you had in mind.  The former has a `hue` directory but no `examples` directory, and the latter has an `examples` directory but no `hue` directory.  On top of that, .gitignore hides `*/examples/*.png`, which suggests the example programs should be run from `palette/palette`, but that's wrong, as you put the inputs are in `palette`, not `palette/palette`.  Follow me? :-[]

(I didn't need to name my top level folder `palette`, but normally doing so doesn't create this kind of confusion.)

I fixed this by creating the folder  `palette/examples`.  If you put one file in that folder, it will be created by `git clone`.

There are many ways to unwind this confusion, but I suggest the following small changes:

- add a sentence to `palette/readme.md `with instructions for running examples 
- rename `palette/examples` to `palette/example-data` -- different from src/examples
- put input files in `palette/example-data/input` (instead of `palette/res`)  
- put outputs in `palette/example-data/output` (instead of `palette/examples`)
- put a readme in `palette/example-data/output` to force its creation by git
- change all the hardwired paths in the example programs accordingly
- correct .gitignore accordingly

I'm happy to do this. :-)

**Comment by Ogeon** [comment]
Thanks for reporting this!

I'm surprised the PNG error is a runtime error, but I'm sure there's a good reason. 🤔 That one seems fixable by just figuring out which Cargo feature to enable in `image`. The defaults were disabled to reduce the build time.

The path problems may stem from the fact that the examples were written before the Cargo workspace was added. They may still be adapted to being ran from the same location as the examples directory, which used to be the project root but isn't anyone. It may also have gone undetected until now because it wasn't possible to run every Cargo command from the root until recently, so I (and I suppose other contributors) didn't spend as much time there.

I don't know what the best approach is, really, but it would be nice to be able to run them from the project root. That would go well together with my plans for the readme files. I would like to have repo specific things in only the repo readme and only crate specific things in the readme that ends up at crates.io. This is a WIP on my table at the moment, so don't worry too much about it. 🙂

And it would also be super nice to avoid having a permanent "trashcan" directory that's just empty, if possible. I'm also open to other ways of outputting the result as long as it's not too complicated for a small example.

Feel free to take on any of these issues. 👍 It's much appreciated! If you want to edit the readme, then do it in the project root only. The rest of them are links to it and will reflect the changes. It will also make my job of rewriting it easier. 😁

**Comment by darakshan** [comment]
I have a version where all example programs now read from example-data/input/* and write to example-data/output/...  If the output directory is absent, it is created.  If example-data/input/* in the root, that's where the examples need to be run from.

Png issue was easily fixed in Cargo.toml.

I have a branch ready to push these changes.  I guess you need to invite me to collaborate :-)

I propose to make a few more substantive changes: split out each simple example from readme_examples, create a helper object used by all examples to manage swatches and save files (and perhaps optionally to the screen), and (maybe) extend the command line handler in color-scheme to work with all examples, so there would be only one "main" and the examples would be more flexible.  These structural changes should make it easier to add new examples and keep the examples simple.

**Comment by Ogeon** [comment]
Sounds like you have the PNG and output location figured out. 👍 I prefer to receive contributions via pull requests. You can submit pull requests from your own fork of this repository without having to be a collaborator, as described in https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request and its linked pages.

As I mentioned before, I'm in the process of rewriting the readme files. My intention is to replace the current readme examples with a new set of snippets that better represents the current feature set. I don't intend to have images for those either, as they have been difficult to verify and maintain, and a bit problematic when publishing on crates.io.

So, while I appreciate your ideas to improve them, I would say it's better to just leave the readme_examples file as it is. It's going to be removed soon.

Let's start with the issues you reported here and get that sorted out first, to not overextend the scope.

**Comment by darakshan** [comment]
This is my first time making a pull request. I couldn't figure it out yesterday, probably due to lack of sleep. :-) This morning it all clicked into place: I first have to *fork* the entire repository into my own github account (now I know what that means!), not just make a local branch on *your* remote repository....

**Comment by Ogeon** [comment]
That's right. I remember it being a bit strange for me too, the first time I had to do it, but it comes with some nice benefits. Now you have your own sandboxed version of the repository where you can experiment without accidentally affecting the upstream version. And I don't have to add everyone as a collaborator all the time. :smile:

**Comment by Ogeon** [comment]
Oh, and don't be afraid to ask if you have any questions. No question is too small.

**Comment by Ogeon** [comment]
I think this one is resolved.
