### ISSUE TITLE
I suggest to change the name

### ISSUE THREAD

**Issue by Blyxyas** [Ogeon/palette#271]
## Description

Changing the name of this crate from palette to **omelete**

<img src="https://docs.google.com/drawings/d/e/2PACX-1vQPGhC0oaRgL3jrQOyPeFD_eticI-zoeKex9kVNzOnKAqB8IbbyEHD_JsHU0_ek7rczGvCKDJtv-K8a/pub?w=960&amp;h=720">

## Motivation

Palette is a name that can describe the crate functionality, that's the problem, names that describe functionality are bad, that's why we like a lot more names like McDonalds, McDonals could sell a lot of things, it could sell air bending machines! Honestly, it is so much better, plus, omelettes taste well enough to be the name of the Rust crate. Thanks for reading

**Comment by Ogeon** [comment]
Hi, thank you for the proposal and the great illustration that really shows the benefits of a name change, but I'm afraid I have to decline. I do agree, though, that omelettes have a lot of good properties and open up for a wide array of possibilities, [not to mention other fun activities you can have with eggs](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fs-media-cache-ak0.pinimg.com%2Foriginals%2F4f%2Fcd%2Fc6%2F4fcdc66f976642b24f3b82f7cf7e71d2.jpg&f=1&nofb=1).

However, I think you may be basing this proposal on a misunderstanding. The word "palette" is already ambiguous and doesn't say exactly what the library does. Not only can it refer to the painter's tool, but it may also have more figurative meanings. And even as a reference to the board on which a painter may choose to put dollops of paint, it is only relevant by a couple of steps of association. If you also include various homophones, such as "pallet" and "palate", the palette of possibilities grows even more.

That said, I'm not sure I see how "omelette" would be allow widening the possibilities, compared to "palette". It wouldn't include color management, would it? The same way "palette" wouldn't seem to include egg management. Otherwise I would argue that "palette" is an equally flexible name.

But for the sake of backwards compatibility (the lib has been around for a while) and due to the fact that I have grown pretty fond of it, I will keep it for now. The name "omelette" remains up for grabs for now. Maybe I decide to pivot completely some day and name it "pirouette" instead.

**Comment by Blyxyas** [comment]
Yes, I guess leaving the name is good too :(
