### ISSUE TITLE
Display P3 (and DCI-P3) support

### ISSUE THREAD

**Issue by marcpabst** [Ogeon/palette#367]
## Description

I'm looking to implement Display P3 support (and potentially also DCI-P3) - as far as I can see, this should mostly encompass copying the sRGB code and changing the primaries to those of DCI-P3 (as the EOTF is the same as in sRGB). I'm happy to do it, if someone agrees to review and merge it.

**Comment by Ogeon** [comment]
Hi, this would be a nice addition, seeing how it's at least relevant within the Apple ecosystem. It should be enough to implement the as RGB standards, from what I have seen.

**Comment by Ogeon** [comment]
Oh and I'll review and merge it, I may just be a bit inactive this coming week or so, to spend time with family and wind down after a busy December.

**Comment by marcpabst** [comment]
> Oh and I'll review and merge it, I may just be a bit inactive this coming week or so, to spend time with family and wind down after a busy December.

That's great to hear! Just wanted to make sure there's interest :) I think both DCI P3 and Display P3 should be fairly easy to add the DCI P3 primaries, as they use D65 as the white point and a gamma 2.4 / sRGB EOTF.

Merry Chrismas!

**Comment by marcpabst** [comment]
And while we're at it, we should probably also add other trivially-to-implement and widely-used colour spaces like AdobeRGB.

**Comment by Ogeon** [comment]
Sure thing, the only reason why it hasn't happened so far is that nobody has asked for it or championed it. 🙂 If you give this a try, it would be nice if you can have modularity in mind. Shared primaries can be a shared type, for example. I'm just mentioning it since there's not much presence for it in the code so far, but it was the original intent.

Merry Christmas to you too!
