### ISSUE TITLE
Issue while LCH -> RGB conversion

### ISSUE THREAD

**Issue by siddhartpai** [Ogeon/palette#77]
I had an RGB pixel which i wanted to shift the hue by 180 , so I initially converted the color to LCH  and then did a hue shift on it , and converted it back to RGB . The converted RGB values are way out of bounds .

`let dominant_color: self::rgb::RGB<u8> = viewer.get_prominent_color( width, height);
let lch_color: Lch = Rgb::from(Srgb::new(dominant_color.r as f32,dominant_color.g as f32,dominant_color.b as f32)).into();
let new_color: Rgb = lch_color.shift_hue(180.0.into()).into();`

Dominant Color : RGB { r: 175, g: 180, b: 171 } 
lch_color : Lch { l: 70.13459, chroma: 3.5053592, hue: LabHue(130.76137) } 
hueshifted : Rgb { red: 232155.52, green: 217398.52, blue: 245035.61 }

**Comment by Ogeon** [comment]
I see that you converted srgb to RGB without dividing by 255. That could be
part of the problem (although one would think it would work ok anyway).
There should be a constructor that takes u8 that does it for you. Try that
and see if it improves.

Den ons 14 feb. 2018 11:44Siddharth Pai <notifications@github.com> skrev:

**Comment by siddhartpai** [comment]
Thanks for that. It worked by dividing the values by 255 before conversion.

**Comment by Ogeon** [comment]
Ok, I guess they got amplified by the scale. The results may still
overshoot a little, since the color spaces doesn't exactly overlap, so you
may still have to clamp the results. Let me know if you get more strange
values, and compare them with an online conversion tool. It's not
completely impossible that there is an error somewhere.

Den ons 14 feb. 2018 17:18Siddharth Pai <notifications@github.com> skrev:
